const ProfilesActionsConstants = {
    SET_ALL_USERS: 'PROFILES_CONSTANTS.SET_ALL_USERS',
    GET_ALL_USERS: 'PROFILES_CONSTANTS.GET_ALL_USERS',

    CHANGE_VALUE: 'PROFILES_CONSTANTS.CHANGE_VALUE',
    SET_ERROR: "PROFILES_CONSTANTS.SET_ERROR",
    SET_COMPLETE: "PROFILES_CONSTANTS.SET_COMPLETE",


   
  };
  
  export {ProfilesActionsConstants}
  