const SignInActionsConstants = {
    CHANGE_VALUE: 'SIGNIN_CONSTANTS.CHANGE_VALUE',
    SIGNIN_USER :'SIGNIN_CONSTANTS.SIGNIN_USER',
    SET_COMPLETE: 'SIGNIN_CONSTANTS.SET_COMPLETE',
    SET_ERROR: 'SIGNIN_CONSTANTS.SET_ERROR',
  };
  
  export {SignInActionsConstants}