const AccountActionsConstants = {
    GET_ALL_REVIEWS: 'ACCOUNT_CONSTANTS.GET_ALL_REVIEWS',
    SET_ALL_REVIEWS: 'ACCOUNT_CONSTANTS.SET_ALL_REVIEWS',
 
    UPDATE_USERNAME: 'ACCOUNT_CONSTANTS.UPDATE_USERNAME',
    UPDATE_LOCATION: 'ACCOUNT_CONSTANTS.UPDATE_lOCATION',

    CHANGE_VALUE: 'ACCOUNT_CONSTANTS.CHANGE_VALUE',
    SET_ERROR: "ACCOUNT_CONSTANTS.SET_ERROR",
    SET_COMPLETE: "ACCOUNT_CONSTANTS.SET_COMPLETE",

    DELETE_REVIEW: "ACCOUNT_CONSTANTS.DELETE_REVIEW",
    SET_DELETE_SUCCESS: "ACCOUNT_CONSTANTS.SET_DELETE_SUCCESS",
    SET_DELETE_ERROR: "ACCOUNT_CONSTANTS.SET_DELETE_ERROR",

    UPDATE_REVIEW: "ACCOUNT_CONSTANTS.UPDATE_REVIEW",
    SET_UPDATE_COMPLETED: "ACCOUNT_CONSTANTS.SET_UPDATE_COMPLETED",
    SET_UPDATE_ERROR: "ACCOUNT_CONSTANTS.SET_UPDATE_ERROR",

    SET_EDIT_REVIEW: "ACCOUNT_CONSTANTS.SET_EDIT_REVIEW",

  };
  
  export {AccountActionsConstants}
  