const ReviewsActionsConstants = {
    GET_ALL_REVIEWS: 'REVIEWS_CONSTANTS.GET_ALL_REVIEWS',
    SET_ALL_REVIEWS: 'REVIEWS_CONSTANTS.SET_ALL_REVIEWS',
    GET_ALL_RESTAURANTS: 'REVIEWS_CONSTANTS.GET_ALL_RESTAURANTS',
    SET_ALL_RESTAURANTS: 'REVIEWS_CONSTANTS.SET_ALL_RESTAURANTS',
    CHANGE_VALUE: 'REVIEWS_CONSTANTS.CHANGE_VALUE',
    ADD_NEW_REVIEW: 'REVIEWS_CONSTANTS.ADD_NEW_REVIEW',
    SET_NEW_REVIEW_COMPLETE: 'REVIEWS_CONSTANTS.SET_NEW_REVIEW_COMPLETE',
    SET_NEW_REVIEW_FAILED: 'REVIEWS_CONSTANTS.SET_NEW_REVIEW_FAILED',
    SEARCH_REVIEWS: 'REVIEWS_CONSTANTS.SEARCH_REVIEWS',
    SORT_REVIEWS_BY_VALUE: 'REVIEWS_CONSTANTS.SORT_REVIEWS_BY_VALUE',
    ADVANCED_SEARCH: 'REVIEWS_CONSTANTS.ADVANCED_SEARCH',
    SET_REVIEWS_ADVANCED_SEARCH_COMPLETE: 'REVIEWS_CONSTANTS.SET_REVIEWS_ADVANCED_SEARCH_COMPLETE',
    SET_NO_REVIEWS: 'REVIEWS_CONSTANTS.SET_NO_REVIEWS',

    
  };
  
  export {ReviewsActionsConstants}
  