const RestaurantsActionsConstants = {
    GET_ALL_RESTAURANTS: 'RESTAURANTS_CONSTANTS.GET_ALL_RESTAURANTS',
    SET_ALL_RESTAURANTS: 'RESTAURANTS_CONSTANTS.SET_ALL_RESTAURANTS',
    CHANGE_VALUE: 'RESTAURANTS_CONSTANTS.CHANGE_VALUE',
    ADD_NEW_RESTAURANT: 'RESTAURANTS_CONSTANTS.ADD_NEW_RESTAURANT',
    SET_NEW_RESTAURANT_COMPLETE: 'RESTAURANTS_CONSTANTS.SET_NEW_RESTAURANT_COMPLETE',
    SET_NEW_RESTAURANT_FAILED: 'RESTAURANTS_CONSTANTS.SET_NEW_RESTAURANT_FAILED',
    GET_RANK_DISTANCE_RESTAURANTS: 'RESTAURANTS_CONSTANTS.GET_RANK_DISTANCE_RESTAURANTS',
    SET_RANK_DISTANCE_RESTAURANTS: 'RESTAURANTS_CONSTANTS.SET_RANK_DISTANCE_RESTAURANTS',
  };
  
  export {RestaurantsActionsConstants}
  