const SignUpActionsConstants = {
    CHANGE_VALUE: 'SIGNUP_CONSTANTS.CHANGE_VALUE',
    CHECK_USER_EXISTS: 'SIGNUP_CONSTANTS.CHECK_USER_EXISTS',
    SET_USER_FREE: 'SIGNUP_CONSTANTS.SET_USER_FREE',
    SET_REGISTRATION_COMPLETE: 'SIGNUP_CONSTANTS.SET_REGISTRATION_COMPLETE',
    SET_REGISTRATION_FAILED: 'SIGNUP_CONSTANTS.SET_REGISTRATION_FAILED',
    REGISTER_USER: 'SIGNUP_CONSTANTS.REGISTER_USER',
  };
  
  export {SignUpActionsConstants}