const { List, Map } = require('immutable');

export default {
    app: Map({
      user: { 
        firstName: '',
        lastName: '',
        username: '',
        password: '',
        location: '',
        picture: '',
        },
      username: '',
      loading: false,
      requireAuth: true,
    }),
    SignUp: Map({
      firstName: '',
      lastName: '',
      username: '',
      password: '',
      location: null,
      picture: '',
      usernameExist: false,
      completed: false,
      error: false, 
      address: '',
      errorMessage: '',
      lat: null,
      lng: null,
      
  }),

  SearchBar: Map({
    address: '',
    errorMessage: '',
    latitude: '',
    longitude: '',
    isGeocoding: false,
  }),
  SignIn: Map({
    username: '',
    password: '',
    completed: false,
    error: false,
}),
  Restaurants: Map({
    name: '',
    location: '',
    lat: null,
    lng: null,
    restaurants: [{"_id":1,"name":"McDonalds", "location":"Tel Aviv"}],
    restaurantDistance: [],
    completed: false,
    error: false,
    basicSearch:false,
    advancedSearch:false,
    averageRank:0,
    radiusFromMe :0,
    userName: '',
}),
Reviews: Map({
  reviews:'',
  restaurantSearch:'',
  user: '',
  bathroomQuality: 0,
  staffKindness: 0,
  cleanliness: 0,
  driveThruQuality:0,
  deliverySpeed : 0,
  foodQuality: 0,
  picture: null,
  restaurant: '',
  completed: false,
  error: false,
  openbathroomQ : false,
  openstaffK:false,
  opencleanin:false,
  opendriveThr:false,
  opendeliverysp:false,
  openfoodqu:false,
  restaurants: [{"_id":1,"name":"aa", "location":"aa"}],
  search: false,
  sortValue:'',
  nameSearch:'',
  locationSearch:'',
  averageSearch:"0",
  username:'',
  addReviewDialogopen: false,
  withDelivery: false,



}),
  Account: Map({
    reviews: [],
    firstName: '',
    lastName: '',
    username: '',
    password: '',
    location: null,
    picture: '',
    completed: false,
    error: false,
    newusername:'',
    newlocation:'',
    newlat:'',
    newlng:'',
    isReviews:false,
    deleteCompleted:false,
    deleteError:false,
    updateCompleted:false,
    updateError:false,  
    reviewId:'', 
    bathroomQuality: 0,
    staffKindness: 0,
    cleanliness: 0,
    driveThruQuality:0,
    deliverySpeed : 0,
    foodQuality: 0,
    picture: null,
    update:false,
    openbathroomQ : false,
    openstaffK:false,
    opencleanin:false,
    opendriveThr:false,
    opendeliverysp:false,
    openfoodqu:false,
    updatePage:false,
    editReviewDialogopen: false,
    modifyDialog: false,
    withDelivery: false,
     

}),
  Profiles: Map({
    users: [],
        completed: false,
    error: false,
}),
};
